import assert from 'node:assert/strict'
import { mkdtemp, readFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { createServer } from 'vite'
import { chromium } from 'playwright'

const output = await mkdtemp(join(tmpdir(), 'pingdom-community-'))
const server = await createServer({ cacheDir: join(output, 'vite-cache'), server: { port: 0, host: '127.0.0.1', open: false }, plugins: [{ name: 'community-qa', configureServer(vite) {
  vite.middlewares.use(async (req, res, next) => {
    if (!req.url.startsWith('/community-qa')) return next()
    res.setHeader('Content-Type', 'text/html')
    res.end(await vite.transformIndexHtml(req.url, (await readFile('index.html', 'utf8')).replace('/src/main.tsx', '/tests/browser/community-fixture.jsx')))
  })
} }] })
let browser, page
try {
  await server.listen()
  browser = await chromium.launch()
  for (const width of [1280, 390]) {
    page = await browser.newPage({ viewport: { width, height: 800 } })
    page.setDefaultTimeout(8000)
    const errors = []
    page.on('pageerror', error => errors.push(error.message))
    await page.route('**/*', route => {
      const url = new URL(route.request().url())
      return (url.hostname === '127.0.0.1' && !url.pathname.startsWith('/api')) || ['fonts.googleapis.com', 'fonts.gstatic.com', 'cdn.jsdelivr.net'].includes(url.hostname) ? route.continue() : route.abort()
    })
    await page.goto(`http://127.0.0.1:${server.httpServer.address().port}/community-qa`)
    await page.evaluate(() => document.fonts.ready)
    const list = page.getByLabel('글 목록 목록', { exact: true })
    await list.getByRole('button', { name: /커뮤니티 글 1 글/ }).waitFor()
    assert.equal(await list.getByRole('button').count(), 10)
    await page.getByLabel('글 페이지네이션').getByLabel('다음 페이지로 이동').click()
    await list.getByRole('button', { name: /커뮤니티 글 11/ }).waitFor()
    assert.equal(await list.getByRole('button').count(), 1)
    await list.getByRole('button').click()
    await page.getByText('댓글 90 원문', { exact: true }).waitFor()
    await page.getByRole('button', { name: /댓글 #90/ }).click()
    await page.getByLabel('댓글 상세', { exact: true }).waitFor()
    await page.getByLabel('댓글 페이지네이션').getByLabel('다음 페이지로 이동').click()
    await page.getByRole('button', { name: /댓글 #100/ }).waitFor()
    assert.equal(await page.getByLabel('댓글 상세', { exact: true }).count(), 0)
    await page.screenshot({ path: join(output, `content-${width}.png`), fullPage: true })
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false)
    await page.getByLabel('카테고리 ID').fill('없는분류')
    await page.getByRole('button', { name: '조회', exact: true }).click()
    await page.getByText('조건에 맞는 결과가 없습니다.').waitFor()
    await page.getByRole('button', { name: '커뮤니티 신고 심사', exact: true }).click()
    await page.getByRole('combobox', { name: '신고 처리 상태' }).click()
    await page.getByRole('option', { name: '수락', exact: true }).click()
    await page.getByRole('button', { name: /신고 #3 · 글/ }).click()
    await page.getByLabel('신고 원문', { exact: true }).waitFor()
    assert.equal(await page.getByRole('button', { name: '수락·숨김', exact: true }).isEnabled(), false)
    await page.getByRole('combobox', { name: '신고 처리 상태' }).click()
    await page.getByRole('option', { name: '처리 대기', exact: true }).click()
    await page.getByRole('button', { name: /신고 #2 · 댓글/ }).click()
    await page.getByText(/원문 연결 정보가 없어/).waitFor()
    assert.equal(await page.getByRole('button', { name: '수락·숨김', exact: true }).isEnabled(), false)
    await page.getByRole('button', { name: /신고 #1 · 댓글/ }).click()
    await page.getByLabel('신고 원문', { exact: true }).getByText('댓글 90 원문').waitFor()
    await page.getByRole('button', { name: '수락·숨김', exact: true }).click()
    await page.getByRole('dialog').waitFor()
    await page.waitForFunction(() => document.querySelector('[role="dialog"]')?.contains(document.activeElement))
    await page.keyboard.press('Escape')
    await page.getByRole('dialog').waitFor({ state: 'hidden' })
    assert.equal(await page.evaluate(() => window.communityQA.requests.filter(r => r.method === 'post').length), 0)
    await page.getByRole('button', { name: '수락·숨김', exact: true }).click()
    await page.getByRole('dialog').getByRole('button', { name: '처리 확정' }).click()
    await page.getByText(/신고 #1: 수락했습니다/).waitFor()
    await page.getByRole('dialog').waitFor({ state: 'hidden' })
    assert.equal(await page.getByRole('button', { name: '수락·숨김', exact: true }).isEnabled(), false)
    await page.getByRole('button', { name: /신고 #4 · 글/ }).click()
    await page.getByLabel('신고 원문', { exact: true }).getByText(/글 3 원문/).waitFor()
    await page.evaluate(() => { window.communityQA.failAfterReview = true })
    await page.getByRole('button', { name: '반려', exact: true }).click()
    await page.getByRole('dialog').getByText(/노출 상태는 변경하지 않습니다/).waitFor()
    await page.getByRole('dialog').getByRole('button', { name: '처리 확정' }).click()
    await page.getByText(/신고 처리는 완료됐지만 화면 갱신에 실패/).waitFor()
    await page.getByRole('dialog').waitFor({ state: 'hidden' })
    await page.screenshot({ path: join(output, `reports-${width}.png`), fullPage: true })
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false)
    assert.deepEqual(await page.evaluate(() => window.communityQA.requests.filter(r => r.method === 'post').map(r => r.url)), ['/admin/community-reports/1/accept', '/admin/community-reports/4/decline'])
    await page.getByRole('button', { name: '운영 이력', exact: true }).click()
    await page.getByRole('button').filter({ hasText: '커뮤니티 신고 수락' }).first().waitFor()
    await page.getByLabel('감사 로그 작업 유형', { exact: true }).fill('COMMUNITY_REPORT_DECLINED')
    await page.getByRole('button', { name: '상세 필터 펼치기' }).click()
    await page.getByLabel('감사 로그 대상 유형', { exact: true }).fill('COMMUNITY_REPORT')
    await page.getByRole('button', { name: '조회', exact: true }).click()
    await page.waitForFunction(() => window.communityQA.requests.some(r => r.url === '/admin/audit-logs' && r.params?.action === 'COMMUNITY_REPORT_DECLINED' && r.params?.targetType === 'COMMUNITY_REPORT'))
    assert.deepEqual(errors, [])
    console.log(`PASS ${width}px: content/comments pagination, filters, missing postId, original, dialog cancel, review, partial failure, audit, no overflow`)
    await page.close()
  }
  console.log(`Screenshots: ${output}`)
} catch (error) {
  if (page && !page.isClosed()) await page.screenshot({ path: join(output, 'failure.png'), fullPage: true })
  console.error(`Screenshots: ${output}`)
  throw error
} finally { await browser?.close(); await server.close() }
