import assert from 'node:assert/strict'
import { mkdtemp, readFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { createServer } from 'vite'
import { chromium } from 'playwright'

const output = await mkdtemp(join(tmpdir(), 'pingdom-256-'))
const server = await createServer({ cacheDir: join(output, 'cache'), server: { port: 0, host: '127.0.0.1', open: false }, plugins: [{ name: 'terms-qa', configureServer(vite) {
  vite.middlewares.use(async (req, res, next) => {
    if (!req.url.startsWith('/terms-qa')) return next()
    res.setHeader('Content-Type', 'text/html')
    res.end(await vite.transformIndexHtml(req.url, (await readFile('index.html', 'utf8')).replace('/src/main.tsx', '/tests/browser/reservation-terms-fixture.jsx')))
  })
} }] })
let browser
try {
  await server.listen(); browser = await chromium.launch()
  for (const [width, height] of [[1920, 1080], [1366, 768], [390, 844]]) {
    const page = await browser.newPage({ viewport: { width, height } })
    const errors = []
    page.on('pageerror', error => errors.push(error.message))
    await page.route('**/*', route => new URL(route.request().url()).hostname === '127.0.0.1' ? route.continue() : route.abort())
    await page.goto(`http://127.0.0.1:${server.httpServer.address().port}/terms-qa`)
    const slot = page.getByRole('button').filter({ hasText: '잔여 5 / 5명' })
    await slot.first().click()
    await page.getByRole('button', { name: '가격·취소 조건', exact: true }).click()
    let dialog = page.getByRole('dialog', { name: '가격·취소 조건', exact: true })
    await dialog.getByText(/아직 설정되지/).waitFor()
    assert.equal(await dialog.getByLabel('1인당 가격', { exact: true }).inputValue(), '')
    const cancellation = dialog.getByLabel('취소 가능 여부', { exact: true })
    const unsavedDialog = page.getByRole('dialog', { name: '저장하지 않은 변경 사항이 있습니다' })
    await cancellation.click()
    await page.getByRole('listbox', { name: '취소 가능 여부', exact: true }).waitFor()
    await page.keyboard.press('Escape')
    assert.equal(await dialog.count(), 1, 'First Escape must close only the dropdown')
    assert.equal(await cancellation.getAttribute('aria-expanded'), 'false')
    assert.equal(await cancellation.evaluate(el => el === document.activeElement), true)
    assert.equal(await unsavedDialog.count(), 0)
    await page.keyboard.press('Escape')
    await dialog.waitFor({ state: 'hidden' })
    const opener = page.getByRole('button', { name: '가격·취소 조건', exact: true })
    assert.equal(await opener.evaluate(el => el === document.activeElement), true)
    await opener.click()
    await dialog.getByLabel('1인당 가격', { exact: true }).fill('1000')
    await dialog.getByLabel('예약당 추가 비용', { exact: true }).fill('50')
    await dialog.getByLabel('통화', { exact: true }).fill('USD')
    await dialog.getByLabel('취소 가능 여부', { exact: true }).click()
    await page.getByRole('option', { name: '기한 내 취소 가능', exact: true }).click()
    await dialog.getByLabel('시작 전 취소 기한(분)', { exact: true }).fill('60')
    assert.equal(await dialog.evaluate(el => el.scrollWidth <= el.clientWidth), true)
    const bounds = await dialog.boundingBox()
    assert.ok(bounds.x >= 0 && bounds.y >= 0 && bounds.x + bounds.width <= width && bounds.y + bounds.height <= height)
    await page.screenshot({ path: join(output, `terms-${width}.png`), fullPage: true })
    await cancellation.click()
    await page.keyboard.press('Escape')
    assert.equal(await dialog.count(), 1)
    assert.equal(await cancellation.getAttribute('aria-expanded'), 'false')
    assert.equal(await unsavedDialog.count(), 0, 'Closing the dropdown must not request discarding edits')
    assert.equal(await dialog.getByLabel('1인당 가격', { exact: true }).inputValue(), '1000')
    await page.keyboard.press('Escape')
    await page.getByRole('dialog', { name: '저장하지 않은 변경 사항이 있습니다' }).getByRole('button', { name: '계속 작성' }).click()
    assert.equal(await dialog.getByLabel('1인당 가격', { exact: true }).inputValue(), '1000')
    await page.evaluate(() => { window.qaMode = 'failure' })
    await dialog.getByRole('button', { name: '조건 저장', exact: true }).click()
    await dialog.getByRole('alert').waitFor()
    assert.equal(await dialog.getByLabel('예약당 추가 비용', { exact: true }).inputValue(), '50')
    await page.evaluate(() => { window.qaMode = 'pending' })
    await dialog.getByRole('button', { name: '조건 저장', exact: true }).click()
    await dialog.getByRole('button', { name: '저장 중' }).waitFor()
    await page.keyboard.press('Escape')
    assert.equal(await dialog.count(), 1)
    assert.equal(await dialog.getByRole('button', { name: '닫기', exact: true }).first().isDisabled(), true)
    await page.evaluate(() => window.qaRelease())
    await dialog.waitFor({ state: 'hidden' })
    assert.equal(await page.evaluate(() => window.qaWrites.length), 2)
    assert.deepEqual(await page.evaluate(() => window.qaWrites.at(-1).body), { unitAmountMinor: 1000, additionalAmountMinor: 50, currency: 'USD', timezone: 'Asia/Seoul', cancellable: true, cancellationCutoffMinutes: 60 })
    await page.reload()
    await slot.first().click()
    await page.getByRole('button', { name: '가격·취소 조건', exact: true }).click()
    dialog = page.getByRole('dialog', { name: '가격·취소 조건', exact: true })
    assert.equal(await dialog.getByLabel('통화', { exact: true }).inputValue(), 'USD')
    await dialog.getByRole('button', { name: '닫기', exact: true }).first().click()
    await dialog.waitFor({ state: 'hidden' })
    await slot.nth(1).click()
    await page.getByRole('button', { name: '가격·취소 조건', exact: true }).click()
    await dialog.getByText('저장된 조건을 수정합니다.').waitFor()
    assert.equal(await dialog.getByLabel('1인당 가격', { exact: true }).inputValue(), '0')
    assert.equal(await dialog.getByLabel('시작 전 취소 기한(분)', { exact: true }).count(), 0)
    await dialog.getByLabel('예약당 추가 비용', { exact: true }).fill('100')
    await page.evaluate(() => { window.qaMode = 'refresh-failure' })
    await dialog.getByRole('button', { name: '조건 저장', exact: true }).click()
    await dialog.waitFor({ state: 'hidden' })
    await page.getByText(/조건은 저장됐지만/).waitFor()
    assert.equal(await page.getByRole('button', { name: '가격·취소 조건', exact: true }).isDisabled(), true)
    await page.evaluate(() => { window.qaMode = 'success' })
    await page.getByRole('button', { name: '시간 목록 다시 시도', exact: true }).click()
    await page.getByRole('button', { name: '가격·취소 조건', exact: true }).click()
    assert.equal(await dialog.getByLabel('예약당 추가 비용', { exact: true }).inputValue(), '100')
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false)
    assert.deepEqual(errors, [])
    await page.close()
  }
  console.log('PASS terms UI: 1920/1366/390, unset/free, saved reload, input preservation, dropdown Escape isolation/focus, dirty dismissal, pending guards, refresh recovery. Screenshots: ' + output)
} finally { await browser?.close(); await server.close() }
