import assert from 'node:assert/strict'
import { mkdtemp, readFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join, resolve } from 'node:path'
import { createServer } from 'vite'
import { chromium } from 'playwright'

const output = await mkdtemp(join(tmpdir(), 'pingdom-243-'))
const server = await createServer({ cacheDir: join(output, 'cache'), server: { host: '127.0.0.1', port: 0, open: false }, plugins: [{ name: 'unsaved-fixture', enforce: 'pre', resolveId(source) { if (source.endsWith('/map/NaverMap')) return resolve('tests/browser/place-map-fixture.jsx') }, configureServer(vite) {
  vite.middlewares.use(async (req, res, next) => {
    if (!['/merchant/menus', '/merchant/campaigns', '/merchant/place-registration', '/merchant/place-application', '/places/events', '/places/information-verification', '/login'].includes(req.url.split('?')[0])) return next()
    res.setHeader('Content-Type', 'text/html')
    res.end(await vite.transformIndexHtml(req.url, (await readFile('index.html', 'utf8')).replace('/src/main.tsx', '/tests/browser/unsaved-changes-fixture.jsx')))
  })
} }] })
let browser, page
try {
  await server.listen()
  browser = await chromium.launch()
  const base = `http://127.0.0.1:${server.httpServer.address().port}`
  console.log(`Screenshots: ${output}`)
  for (const [width, height] of [[1920, 1080], [1366, 768], [390, 844]]) {
    page = await browser.newPage({ viewport: { width, height } })
    page.setDefaultTimeout(10000)
    const errors = []
    page.on('pageerror', error => errors.push(error.message))
    await page.route('**/*', route => {
      const url = new URL(route.request().url())
      return (url.hostname === '127.0.0.1' && !url.pathname.startsWith('/api')) || ['fonts.googleapis.com', 'fonts.gstatic.com', 'cdn.jsdelivr.net'].includes(url.hostname) ? route.continue() : route.abort()
    })
    const warning = page.getByRole('dialog', { name: '저장하지 않은 변경 사항이 있습니다', exact: true })
    const name = page.getByRole('textbox', { name: '메뉴명 (필수)', exact: true })
    const selectMenu = id => page.getByRole('button', { name: new RegExp(`합성 메뉴 ${id}`) })
    await page.goto(`${base}/merchant/menus`)
    await name.fill('미저장 메뉴')
    await selectMenu(1).click()
    await warning.waitFor()
    assert.equal(await warning.evaluate(element => element.scrollWidth > element.clientWidth), false)
    await page.screenshot({ path: join(output, `menu-warning-${width}.png`) })
    await warning.getByRole('button', { name: '계속 작성', exact: true }).click()
    assert.equal(await name.inputValue(), '미저장 메뉴')
    await selectMenu(1).click()
    await warning.getByRole('button', { name: '변경 버리고 이동', exact: true }).click()
    await name.filter({ visible: true }).waitFor()
    assert.equal(await name.inputValue(), '합성 메뉴 1')
    await name.fill('수정 중')
    await name.fill('합성 메뉴 1')
    await selectMenu(2).click()
    assert.equal(await warning.count(), 0, 'reverted inputs are clean')
    assert.equal(await name.inputValue(), '합성 메뉴 2')
    const orderRequests = () => page.evaluate(() => window.qaRequests.filter(request => request.method === 'patch' && request.url.endsWith('/order')).length)
    await name.fill('순서 변경 전 수정')
    await page.getByRole('button', { name: '위로 이동', exact: true }).click()
    await warning.waitFor()
    assert.equal(await orderRequests(), 0, 'reorder waits for the unsaved decision')
    await page.screenshot({ path: join(output, `menu-order-warning-${width}.png`) })
    await warning.getByRole('button', { name: '계속 작성', exact: true }).click()
    assert.equal(await name.inputValue(), '순서 변경 전 수정')
    assert.equal(await orderRequests(), 0, 'canceling reorder never calls the API')
    await page.getByRole('button', { name: '위로 이동', exact: true }).click()
    await warning.getByRole('button', { name: '변경 버리고 이동', exact: true }).click()
    await page.waitForFunction(() => document.querySelector('input[maxlength="100"]')?.value === '합성 메뉴 2')
    assert.equal(await orderRequests(), 1, 'confirming reorder calls the API once')
    await page.getByRole('button', { name: '아래로 이동', exact: true }).click()
    await page.waitForFunction(() => window.qaRequests.filter(request => request.url.endsWith('/order')).length === 2)
    await name.waitFor()
    assert.equal(await warning.count(), 0, 'pristine reorder needs no confirmation')
    await name.fill('매장 이동 전 수정')
    await page.getByRole('combobox', { name: '메뉴를 관리할 장소 선택', exact: true }).click()
    await page.getByRole('option', { name: '합성 매장 2 · 합성 주소 2 · #2', exact: true }).click()
    await warning.getByRole('button', { name: '계속 작성', exact: true }).click()
    assert.equal(await name.inputValue(), '매장 이동 전 수정')
    await page.getByRole('button', { name: '새로고침', exact: true }).click()
    await warning.getByRole('button', { name: '변경 버리고 이동', exact: true }).click()
    await name.waitFor()
    await name.fill('실패해도 유지')
    await page.evaluate(() => { window.qaMode = 'failure' })
    await page.getByRole('button', { name: '변경 사항 저장', exact: true }).click()
    await page.getByRole('alert').filter({ hasText: '합성 저장 실패' }).waitFor()
    assert.equal(await name.inputValue(), '실패해도 유지')
    await selectMenu(1).click()
    await warning.getByRole('button', { name: '계속 작성', exact: true }).click()
    await page.evaluate(() => { window.qaMode = 'success' })
    await page.getByRole('button', { name: '변경 사항 저장', exact: true }).click()
    await page.getByText('메뉴 정보를 저장했습니다.', { exact: true }).waitFor()
    await selectMenu(1).click()
    assert.equal(await warning.count(), 0, 'successful save updates the baseline')
    await page.getByRole('button', { name: '이벤트 관리', exact: true }).click()
    await page.waitForURL('**/merchant/campaigns')
    await page.getByRole('button', { name: '메뉴 관리', exact: true }).click()
    await name.fill('뒤로가기 보호')
    await page.goBack()
    await warning.getByRole('button', { name: '계속 작성', exact: true }).click()
    assert.match(page.url(), /merchant\/menus$/)
    assert.equal(await name.inputValue(), '뒤로가기 보호')
    await page.goBack()
    await warning.getByRole('button', { name: '변경 버리고 이동', exact: true }).click()
    await page.waitForURL('**/merchant/campaigns')

    const campaignTitle = page.getByRole('textbox', { name: '이벤트 제목 (필수)', exact: true })
    await campaignTitle.fill('브랜드 추가 전 제목')
    await page.getByRole('button', { name: '브랜드 추가', exact: true }).click()
    const brand = page.getByRole('dialog', { name: '브랜드 등록', exact: true })
    await brand.getByRole('button', { name: '취소', exact: true }).click()
    assert.equal(await warning.count(), 0, 'a pristine nested dialog ignores its dirty parent')
    await page.getByRole('button', { name: '브랜드 추가', exact: true }).click()
    await brand.getByRole('textbox', { name: '브랜드명 (필수)', exact: true }).fill('새 합성 브랜드')
    await brand.getByRole('button', { name: '취소', exact: true }).click()
    await warning.getByRole('button', { name: '계속 작성', exact: true }).click()
    await brand.getByRole('button', { name: '저장', exact: true }).click()
    await brand.waitFor({ state: 'hidden' })
    assert.equal(await campaignTitle.inputValue(), '브랜드 추가 전 제목')
    assert.match(await page.getByRole('combobox', { name: '이벤트 브랜드', exact: true }).textContent(), /새 합성 브랜드/)
    await page.getByRole('button', { name: '새로고침', exact: true }).click()
    await warning.getByRole('button', { name: '변경 버리고 이동', exact: true }).click()
    await campaignTitle.waitFor()

    await page.goto(`${base}/merchant/place-registration`)
    await page.locator('input[type="file"]').setInputFiles({ name: 'synthetic-proof.pdf', mimeType: 'application/pdf', buffer: Buffer.from('synthetic document') })
    await page.getByRole('button', { name: '파일 추가', exact: true }).click()
    await page.getByRole('button', { name: '새 장소 등록 신청', exact: true }).click()
    await warning.getByRole('button', { name: '계속 작성', exact: true }).click()
    await page.getByText('synthetic-proof.pdf', { exact: true }).waitFor()
    let reloadWarning = false
    page.once('dialog', async native => { assert.equal(native.type(), 'beforeunload'); reloadWarning = true; await native.dismiss() })
    await page.reload({ timeout: 1500 }).catch(error => { if (!reloadWarning || !/ERR_ABORTED|Timeout/.test(error.message)) throw error })
    assert.equal(reloadWarning, true, 'browser reload displays the native warning')
    await page.getByText('synthetic-proof.pdf', { exact: true }).waitFor()
    await page.getByRole('button', { name: '새 장소 등록 신청', exact: true }).click()
    await warning.getByRole('button', { name: '변경 버리고 이동', exact: true }).click()
    assert.equal(await page.getByText('synthetic-proof.pdf', { exact: true }).count(), 0)
    await page.goto(`${base}/merchant/place-application`)
    const legalName = page.getByRole('textbox', { name: /법적 성명/ })
    await legalName.fill('미저장 신청자')
    await page.getByRole('button', { name: '새 운영 장소 신청', exact: true }).click()
    await warning.getByRole('button', { name: '계속 작성', exact: true }).click()
    assert.equal(await legalName.inputValue(), '미저장 신청자')
    await page.getByRole('button', { name: '로그아웃', exact: true }).first().click()
    await page.waitForURL('**/login')
    assert.equal(await warning.count(), 0, 'logout is never blocked')
    await page.goto(`${base}/merchant/menus`)
    await name.fill('계정 전환 전 입력')
    await page.evaluate(() => window.qaSwitchAccount())
    await page.waitForFunction(() => document.querySelector('input[maxlength="100"]')?.value === '')
    assert.equal(await warning.count(), 0)
    await name.fill('인증 만료 전 입력')
    await page.getByRole('textbox', { name: '가격 (필수)', exact: true }).fill('12000')
    await page.evaluate(() => { window.qaMode = 'unauthorized' })
    await page.getByRole('button', { name: '메뉴 등록', exact: true }).click()
    await page.waitForURL('**/login')
    assert.equal(await warning.count(), 0, 'expired authentication is never blocked')

    await page.goto(`${base}/places/events`)
    await page.getByRole('button', { name: '이벤트 등록', exact: true }).click()
    const edit = page.getByRole('dialog', { name: '기간형 이벤트 등록', exact: true })
    await edit.getByRole('textbox', { name: /이벤트 제목/ }).fill('미저장 행사')
    const dateTrigger = edit.getByRole('button', { name: /^이벤트 시작 일시,/ })
    const calendar = page.getByRole('dialog', { name: '이벤트 시작 일시', exact: true })
    await dateTrigger.click()
    await calendar.waitFor()
    await dateTrigger.press('Escape')
    await calendar.waitFor({ state: 'hidden' })
    assert.equal(await warning.count(), 0, 'Escape on the trigger closes only its calendar')
    await dateTrigger.click()
    await calendar.getByRole('button', { name: '다음 달', exact: true }).press('Escape')
    await calendar.waitFor({ state: 'hidden' })
    assert.equal(await dateTrigger.evaluate(element => element === document.activeElement), true, 'calendar restores trigger focus')
    assert.equal(await warning.count(), 0)
    await dateTrigger.click()
    const timeTrigger = calendar.getByRole('button', { name: /^시간 선택,/ })
    const timePopup = page.getByRole('dialog', { name: '시간 선택', exact: true })
    await timeTrigger.press('ArrowDown')
    await timePopup.waitFor()
    await page.screenshot({ path: join(output, `event-time-picker-${width}.png`) })
    await timePopup.getByRole('option', { name: '00', exact: true }).first().press('Escape')
    await timePopup.waitFor({ state: 'hidden' })
    assert.equal(await timeTrigger.evaluate(element => element === document.activeElement), true, 'time popup restores trigger focus')
    assert.equal(await calendar.isVisible(), true, 'nested time Escape preserves its calendar')
    assert.equal(await warning.count(), 0)
    await timeTrigger.press('Escape')
    await calendar.waitFor({ state: 'hidden' })
    assert.equal(await edit.isVisible(), true)
    assert.equal(await warning.count(), 0, 'picker Escape leaves the dirty editor intact')
    await edit.getByRole('textbox', { name: /이벤트 제목/ }).press('Escape')
    await warning.waitFor()
    await warning.getByRole('button', { name: '변경 버리고 이동', exact: true }).focus()
    await page.keyboard.press('Tab')
    assert.equal(await warning.evaluate(element => element.contains(document.activeElement)), true)
    await page.keyboard.press('Escape')
    assert.equal(await warning.count(), 0, 'Escape dismisses only the confirmation, not its edit dialog')
    assert.equal(await edit.getByRole('textbox', { name: /이벤트 제목/ }).inputValue(), '미저장 행사')
    await edit.getByRole('button', { name: '취소', exact: true }).click()
    await warning.getByRole('button', { name: '계속 작성', exact: true }).click()
    assert.equal(await edit.getByRole('textbox', { name: /이벤트 제목/ }).inputValue(), '미저장 행사')
    await edit.getByRole('button', { name: '닫기', exact: true }).click()
    await page.screenshot({ path: join(output, `event-warning-${width}.png`) })
    await warning.getByRole('button', { name: '변경 버리고 이동', exact: true }).click()
    assert.equal(await edit.count(), 0)

    await page.goto(`${base}/places/information-verification?placeId=1`)
    await page.getByRole('button', { name: '증빙 등록', exact: true }).click()
    const evidence = page.getByRole('dialog', { name: '정보 증빙 등록', exact: true })
    await evidence.getByRole('textbox', { name: /설명/ }).fill('미저장 증빙 설명')
    await evidence.getByRole('button', { name: '취소', exact: true }).click()
    await warning.getByRole('button', { name: '계속 작성', exact: true }).click()
    assert.equal(await evidence.getByRole('textbox', { name: /설명/ }).inputValue(), '미저장 증빙 설명')
    await evidence.getByRole('button', { name: '닫기', exact: true }).click()
    await warning.getByRole('button', { name: '변경 버리고 이동', exact: true }).click()
    await page.getByRole('tab', { name: /재확인/ }).click()
    await page.getByRole('button', { name: '재확인 요청', exact: true }).click()
    const reverification = page.getByRole('dialog', { name: '장소 정보 재확인 요청', exact: true })
    await reverification.getByRole('textbox', { name: /요청 사유/ }).fill('미저장 재확인 사유')
    await reverification.getByRole('button', { name: /^재확인 응답 기한,/ }).click()
    const dueCalendar = page.getByRole('dialog', { name: '재확인 응답 기한', exact: true })
    await dueCalendar.getByRole('button', { name: '다음 달', exact: true }).press('Escape')
    await dueCalendar.waitFor({ state: 'hidden' })
    assert.equal(await warning.count(), 0, 'reverification calendar Escape does not open the unsaved confirmation')
    assert.equal(await reverification.getByRole('textbox', { name: /요청 사유/ }).inputValue(), '미저장 재확인 사유')
    await reverification.getByRole('button', { name: '취소', exact: true }).click()
    await warning.getByRole('button', { name: '변경 버리고 이동', exact: true }).click()
    assert.equal(await reverification.count(), 0)
    await page.getByRole('tab', { name: /신고/ }).click()
    await page.getByRole('button', { name: /신고 #1 · 장소 #1/ }).click()
    await page.getByRole('button', { name: '신고 검토', exact: true }).click()
    const report = page.getByRole('dialog', { name: '신고 검토', exact: true })
    await report.getByRole('textbox', { name: /판정 근거/ }).fill('미저장 신고 근거')
    await report.getByRole('button', { name: '취소', exact: true }).click()
    await warning.getByRole('button', { name: '계속 작성', exact: true }).click()
    assert.equal(await report.getByRole('textbox', { name: /판정 근거/ }).inputValue(), '미저장 신고 근거')
    await report.getByRole('button', { name: '닫기', exact: true }).click()
    await warning.getByRole('button', { name: '변경 버리고 이동', exact: true }).click()
    assert.equal(await report.count(), 0)
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false)
    assert.deepEqual(errors, [])
    console.log(`${width}x${height} unsaved forms, files, history, keyboard, authentication PASS`)
    await page.close()
  }
} catch (error) {
  if (page && !page.isClosed()) { await page.screenshot({ path: join(output, 'failure.png') }); console.log(page.url(), await page.evaluate(() => window.qaRequests)) }
  throw error
} finally { await browser?.close(); await server.close() }
