import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { AdminNotificationButton } from '../../components/adminNotification/AdminNotificationButton'
import { ADMIN_MAIN_SCROLL_AREA_ID } from '../../constants/layout'
import { useAdminVisitorVerifications } from '../../hooks/useAdminVisitorVerifications'
import { useAuth } from '../../hooks/useAuth'
import type { VisitorVerificationCorrection, VisitorVerificationReport, VisitorVerificationStatus } from '../../types/adminVisitorVerification.types'
import * as Shell from '../place/PlaceManagePage.styles'
import * as Shared from '../placeMerge/PlaceMergePage.styles'
import * as S from '../placeVerification/PlaceVerificationPage.styles'

type Tab = 'reports' | 'corrections'
type Selected = { kind: Tab; item: VisitorVerificationReport | VisitorVerificationCorrection }
const STATUS: Record<VisitorVerificationStatus, string> = { SUBMITTED: '심사 대기', ACCEPTED: '승인', REJECTED: '반려' }
const TYPE_LABELS: Record<string, string> = { PLACE_INFORMATION: '장소 정보', OPERATING_HOURS: '운영 시간', LOCATION: '위치', CLOSED_PLACE: '폐업 장소', WAIT_TIME: '대기 시간', LANGUAGE_SUPPORT: '언어 지원', COUPON_USAGE: '쿠폰 사용', CROWD_LEVEL: '혼잡도', OTHER: '기타' }
function formatDate(value?: string | null) { if (!value) return '정보 없음'; const date = new Date(value); return Number.isNaN(date.getTime()) ? value : new Intl.DateTimeFormat('ko-KR', { dateStyle: 'medium', timeStyle: 'short' }).format(date) }

function VisitorVerificationPage() {
  const navigate = useNavigate(); const { logout, user } = useAuth(); const hook = useAdminVisitorVerifications()
  const [tab, setTab] = useState<Tab>('reports'); const [selected, setSelected] = useState<Selected | null>(null); const [decision, setDecision] = useState<'ACCEPTED' | 'REJECTED' | null>(null); const [reviewNote, setReviewNote] = useState(''); const [formError, setFormError] = useState('')
  const adminIdentifier = user?.username || (typeof user?.id === 'number' ? `ID ${user.id}` : '관리자 계정')
  const items = tab === 'reports' ? hook.reports : hook.corrections; const status = tab === 'reports' ? hook.reportStatus : hook.correctionStatus; const page = tab === 'reports' ? hook.reportPage : hook.correctionPage; const total = tab === 'reports' ? hook.reportTotal : hook.correctionTotal; const totalPages = tab === 'reports' ? hook.reportTotalPages : hook.correctionTotalPages; const hasNext = tab === 'reports' ? hook.reportHasNext : hook.correctionHasNext
  const requesterId = (item: VisitorVerificationReport | VisitorVerificationCorrection) => 'reporterUserId' in item ? item.reporterUserId : item.requesterUserId
  const submit = async () => { if (!selected || !decision || hook.isReviewing) return; if (!reviewNote.trim()) { setFormError('심사 근거를 입력해주세요.'); return } if (await hook.review(selected.kind, selected.item.id, decision, reviewNote.trim())) { setDecision(null); setSelected(null) } }

  return <Shell.AppShell>
    <Shell.SideNav aria-label="관리자 메뉴"><Shell.SideHeader><Shell.BrandLockup><Shell.BrandLogo src="/pingdom-logo.png" alt="PingDom" /></Shell.BrandLockup></Shell.SideHeader><Shell.SideMenu><Shell.MenuButton type="button" $active onClick={() => navigate('/dashboard')}><Shell.MaterialIcon aria-hidden="true">dashboard</Shell.MaterialIcon><span>대시보드</span></Shell.MenuButton><Shell.MenuButton type="button" onClick={() => navigate('/places')}><Shell.MaterialIcon aria-hidden="true">location_on</Shell.MaterialIcon><span>장소 관리</span></Shell.MenuButton><Shell.MenuButton type="button" onClick={() => navigate('/main')}><Shell.MaterialIcon aria-hidden="true">description</Shell.MaterialIcon><span>게시글 관리</span></Shell.MenuButton><Shell.MenuButton type="button" onClick={() => navigate('/bans')}><Shell.MaterialIcon aria-hidden="true">block</Shell.MaterialIcon><span>사용자 밴</span></Shell.MenuButton></Shell.SideMenu><Shell.SideFooter><Shell.AdminProfile><Shell.AdminProfileIcon><Shell.MaterialIcon aria-hidden="true">admin_panel_settings</Shell.MaterialIcon></Shell.AdminProfileIcon><Shell.AdminProfileText><strong>{adminIdentifier}</strong><span>관리자</span></Shell.AdminProfileText></Shell.AdminProfile><Shell.LogoutButton type="button" onClick={() => { void logout(); navigate('/login', { replace: true }) }}><Shell.MaterialIcon aria-hidden="true">logout</Shell.MaterialIcon><span>로그아웃</span></Shell.LogoutButton></Shell.SideFooter></Shell.SideNav>
    <Shell.MainArea id={ADMIN_MAIN_SCROLL_AREA_ID}><Shell.TopBar><Shell.TopTitleGroup><Shell.TopTitle>방문자 검증 심사</Shell.TopTitle></Shell.TopTitleGroup><Shell.TopActions><AdminNotificationButton /><Shell.IconButton type="button" aria-label="목록 새로고침" disabled={hook.isLoading || hook.isReviewing} onClick={() => void hook.fetchItems(tab, status, page)}><Shell.MaterialIcon aria-hidden="true">refresh</Shell.MaterialIcon></Shell.IconButton></Shell.TopActions></Shell.TopBar><Shared.Content><Shared.PageStack>
      <Shared.PageHeader><div><Shared.Eyebrow>Trust Score &gt; 방문자 검증</Shared.Eyebrow><Shared.PageTitle>방문자 검증 제보 및 정정 심사</Shared.PageTitle><Shared.PageDescription>방문자가 제출한 장소 현장 정보와 정정 요청을 근거별로 검토합니다.</Shared.PageDescription></div><Shared.HeaderActions><Shared.HeaderButton type="button" onClick={() => navigate('/trust-score')}>Trust Score 운영</Shared.HeaderButton></Shared.HeaderActions></Shared.PageHeader>
      <S.TabList role="tablist"><S.TabButton type="button" role="tab" $active={tab === 'reports'} onClick={() => { setTab('reports'); setSelected(null) }}><Shell.MaterialIcon aria-hidden="true">fact_check</Shell.MaterialIcon>검증 제보</S.TabButton><S.TabButton type="button" role="tab" $active={tab === 'corrections'} onClick={() => { setTab('corrections'); setSelected(null) }}><Shell.MaterialIcon aria-hidden="true">edit_note</Shell.MaterialIcon>정정 요청</S.TabButton></S.TabList>
      {hook.actionErrorMessage ? <Shared.Notice $variant="error">{hook.actionErrorMessage}</Shared.Notice> : null}{hook.successMessage ? <Shared.Notice $variant="success">{hook.successMessage}</Shared.Notice> : null}{hook.errorMessage ? <Shared.Notice $variant="error">{hook.errorMessage}</Shared.Notice> : null}
      <Shared.Panel><Shared.PanelHeader><div><Shared.PanelTitle>심사 상태</Shared.PanelTitle><Shared.PanelDescription>{tab === 'reports' ? '방문자 제보' : '정정 요청'} 상태별 목록을 조회합니다.</Shared.PanelDescription></div><S.Select value={status} onChange={(event) => { setSelected(null); void hook.fetchItems(tab, event.target.value as VisitorVerificationStatus | '', 1) }}><option value="">전체</option>{Object.entries(STATUS).map(([value,label]) => <option key={value} value={value}>{label}</option>)}</S.Select></Shared.PanelHeader></Shared.Panel>
      <Shared.Workspace><Shared.Panel><Shared.PanelHeader><div><Shared.PanelTitle>{tab === 'reports' ? '검증 제보' : '정정 요청'}</Shared.PanelTitle><Shared.PanelDescription>항목을 선택해 상세 근거를 확인합니다.</Shared.PanelDescription></div><Shared.PanelCount>{total.toLocaleString()}건</Shared.PanelCount></Shared.PanelHeader><Shared.ScrollArea>{hook.isLoading && items.length === 0 ? <Shared.EmptyState><strong>목록을 불러오는 중입니다.</strong></Shared.EmptyState> : items.length === 0 ? <Shared.EmptyState><strong>조건에 맞는 항목이 없습니다.</strong></Shared.EmptyState> : <S.CardList>{items.map((item) => <S.RecordButton key={item.id} type="button" $selected={selected?.item.id === item.id && selected.kind === tab} onClick={() => setSelected({ kind: tab, item })}><S.RecordHeader><S.RecordTitle>{tab === 'reports' ? '제보' : '정정'} #{item.id} · 장소 #{item.placeId}</S.RecordTitle><S.StatusBadge $tone={item.status === 'ACCEPTED' ? 'success' : item.status === 'REJECTED' ? 'danger' : 'warning'}>{STATUS[item.status]}</S.StatusBadge></S.RecordHeader><S.RecordMeta>사용자 #{requesterId(item)} · {TYPE_LABELS[item.reportType]} · {formatDate(item.createdAt)}</S.RecordMeta><S.RecordDescription>{item.description}</S.RecordDescription></S.RecordButton>)}</S.CardList>}</Shared.ScrollArea><S.Pagination><Shared.SecondaryButton type="button" disabled={page <= 1 || hook.isLoading} onClick={() => { setSelected(null); void hook.fetchItems(tab, status, page - 1) }}>이전</Shared.SecondaryButton><span>{Math.max(page,1)} / {Math.max(totalPages,1)}</span><Shared.SecondaryButton type="button" disabled={!hasNext || hook.isLoading} onClick={() => { setSelected(null); void hook.fetchItems(tab, status, page + 1) }}>다음</Shared.SecondaryButton></S.Pagination></Shared.Panel>
        <Shared.Panel><Shared.PanelHeader><div><Shared.PanelTitle>제출 근거 상세</Shared.PanelTitle><Shared.PanelDescription>장소·현장 정보와 외부 증빙을 확인합니다.</Shared.PanelDescription></div></Shared.PanelHeader><Shared.CompareBody>{!selected ? <Shared.EmptyState><strong>심사할 항목을 선택해주세요.</strong></Shared.EmptyState> : <><S.RecordHeader><div><S.RecordTitle>{selected.kind === 'reports' ? '제보' : '정정'} #{selected.item.id}</S.RecordTitle><S.RecordMeta>사용자 #{requesterId(selected.item)} · 장소 #{selected.item.placeId}</S.RecordMeta></div><S.StatusBadge $tone={selected.item.status === 'ACCEPTED' ? 'success' : selected.item.status === 'REJECTED' ? 'danger' : 'warning'}>{STATUS[selected.item.status]}</S.StatusBadge></S.RecordHeader><S.RecordDescription>{selected.item.description}</S.RecordDescription><S.DetailGrid><S.DetailItem><dt>제보 유형</dt><dd>{TYPE_LABELS[selected.item.reportType]}</dd></S.DetailItem><S.DetailItem><dt>대기 시간</dt><dd>{selected.item.waitTimeMinutes === null ? '해당 없음' : `${selected.item.waitTimeMinutes}분`}</dd></S.DetailItem><S.DetailItem><dt>언어</dt><dd>{selected.item.languageCode || '해당 없음'}</dd></S.DetailItem><S.DetailItem><dt>쿠폰 사용</dt><dd>{selected.item.couponUsageStatus || '해당 없음'}</dd></S.DetailItem><S.DetailItem><dt>혼잡도</dt><dd>{selected.item.crowdLevel || '해당 없음'}</dd></S.DetailItem><S.DetailItem><dt>심사 메모</dt><dd>{selected.item.reviewNote || '미심사'}</dd></S.DetailItem></S.DetailGrid>{selected.item.evidenceUrl ? <S.InlineActions><S.Link href={selected.item.evidenceUrl} target="_blank" rel="noreferrer">제출 증빙 열기</S.Link></S.InlineActions> : null}{selected.item.status === 'SUBMITTED' ? <S.InlineActions><Shared.SecondaryButton type="button" disabled={hook.isReviewing} onClick={() => { setDecision('REJECTED'); setReviewNote(''); setFormError('') }}>반려</Shared.SecondaryButton><Shared.PrimaryButton type="button" disabled={hook.isReviewing} onClick={() => { setDecision('ACCEPTED'); setReviewNote(''); setFormError('') }}>승인</Shared.PrimaryButton></S.InlineActions> : null}</>}</Shared.CompareBody></Shared.Panel>
      </Shared.Workspace>
    </Shared.PageStack></Shared.Content></Shell.MainArea>
    {decision && selected ? <Shared.ModalOverlay role="presentation" onMouseDown={() => !hook.isReviewing && setDecision(null)}><Shared.Modal role="dialog" aria-modal="true" aria-labelledby="visitor-review-title" onMouseDown={(event) => event.stopPropagation()}><Shared.ModalHeader><Shared.ModalTitle id="visitor-review-title">{selected.kind === 'reports' ? '검증 제보' : '정정 요청'} {decision === 'ACCEPTED' ? '승인' : '반려'}</Shared.ModalTitle><Shared.ModalCloseButton type="button" aria-label="닫기" disabled={hook.isReviewing} onClick={() => setDecision(null)}><Shell.MaterialIcon aria-hidden="true">close</Shell.MaterialIcon></Shared.ModalCloseButton></Shared.ModalHeader><Shared.ModalBody><Shared.ModalWarning>장소 #{selected.item.placeId}의 현장 정보에 심사 결과가 반영됩니다.</Shared.ModalWarning><S.Section><S.Field>심사 근거 *<S.TextArea value={reviewNote} maxLength={500} disabled={hook.isReviewing} onChange={(event) => { setReviewNote(event.target.value); setFormError('') }} /></S.Field></S.Section>{formError || hook.actionErrorMessage ? <Shared.Notice $variant="error">{formError || hook.actionErrorMessage}</Shared.Notice> : null}</Shared.ModalBody><Shared.ModalFooter><Shared.SecondaryButton type="button" disabled={hook.isReviewing} onClick={() => setDecision(null)}>취소</Shared.SecondaryButton><Shared.PrimaryButton type="button" disabled={hook.isReviewing} onClick={() => void submit()}>{hook.isReviewing ? '처리 중' : '심사 확정'}</Shared.PrimaryButton></Shared.ModalFooter></Shared.Modal></Shared.ModalOverlay> : null}
  </Shell.AppShell>
}

export default VisitorVerificationPage
