// 관리자 웹에서 공통으로 사용할 스타일 기준입니다.
export const semanticColors = {
  primary: {
    normal: '#FF1956',
    alternative: '#FF4A75',
    assistive: '#FFC9D3',
  },
  secondary: {
    normal: '#BFC1C1',
    alternative: '#D1D4D5',
    assistive: '#F8F8F8',
  },
  label: {
    normal: '#0C0C0D',
    strong: '#000000',
    neutral: '#3B3B40',
    alternative: '#5E5E66',
    assistive: '#767680',
    disabled: '#EFEFEF',
  },
  line: {
    normal: '#E4E4E5',
    neutral: '#F2F2F3',
    alternative: '#F6F6F7',
  },
  fill: {
    normal: '#F6F6F7',
    neutral: '#F2F2F3',
    alternative: '#E4E4E5',
    support: '#FFFFFF',
    assistive: '#FFFFFF',
  },
  background: {
    normal: '#FFFFFF',
    neutral: '#F2F2F3',
    alternative: '#FCFCFD',
  },
  static: {
    black: '#000000',
    white: '#FFFFFF',
    error: '#EE2B2B',
    info: '#008BFF',
    success: '#20DF33',
    warning: '#FFCC00',
  },
} as const

export const adminColors = {
  background: semanticColors.background.alternative,
  surface: semanticColors.background.normal,
  surfaceLow: semanticColors.fill.normal,
  surfaceContainer: semanticColors.fill.neutral,
  surfaceHigh: semanticColors.fill.alternative,
  surfaceHighest: semanticColors.secondary.assistive,
  border: semanticColors.line.normal,
  borderSoft: semanticColors.line.neutral,
  borderDark: semanticColors.secondary.normal,
  text: semanticColors.label.normal,
  strongText: semanticColors.label.strong,
  muted: semanticColors.label.alternative,
  softText: semanticColors.label.assistive,
  placeholder: semanticColors.label.assistive,
  disabled: semanticColors.label.disabled,
  primary: semanticColors.primary.normal,
  primaryHover: semanticColors.primary.alternative,
  primarySoft: semanticColors.primary.assistive,
  primaryTint: '#FF195614',
  primaryText: semanticColors.static.white,
  error: semanticColors.static.error,
  errorTint: '#EE2B2B14',
  info: semanticColors.static.info,
  success: semanticColors.static.success,
  warning: semanticColors.static.warning,
  overlay: '#00000073',
  softOverlay: '#FFFFFFEB',
  shadow: '#00000014',
  strongShadow: '#0000002E',
} as const

export const theme = {
  semanticColors,
  adminColors,
  color: {
    background: adminColors.background,
    surface: adminColors.surface,
    text: adminColors.text,
    mutedText: adminColors.muted,
    border: adminColors.border,
    primary: adminColors.primary,
    danger: adminColors.error,
  },
  space: {
    xs: '4px',
    sm: '8px',
    md: '16px',
    lg: '24px',
    xl: '32px',
  },
  radius: {
    sm: '4px',
    md: '8px',
  },
} as const
