import { useCallback, useEffect, useRef, useState } from 'react'
import * as api from '../api/adminScoutApi'
import { getAuthErrorMessage } from '../api/authError'
import { isApiError } from '../api/customAxios'
import type { AdminScoutErrorResponse, ScoutFieldReport, ScoutFieldReportStatus, ScoutProfile, ScoutProfileStatus } from '../types/adminScout.types'
import { logDebugError } from '../utils/debugLogger'
import { useAuth } from './useAuth'
type Action = 'profile' | 'eligibility' | 'report'
const CATEGORIES = { unauthorized: '로그인이 필요합니다.', forbidden: '관리자 권한이 필요합니다.', 'not-found': 'Scout 프로필 또는 제보를 찾을 수 없습니다.', conflict: '현재 상태에서 처리할 수 없습니다.', network: '서버에 연결할 수 없습니다.', 'request-blocked': '서버 응답을 읽지 못했습니다.', timeout: '응답이 지연되고 있습니다.', server: '서버 오류가 발생했습니다.' }
export function useAdminScouts() {
  const { clearAuth } = useAuth(); const [profileStatus, setProfileStatus] = useState<ScoutProfileStatus | ''>('PENDING'); const [reportStatus, setReportStatus] = useState<ScoutFieldReportStatus | ''>('SUBMITTED'); const [profiles, setProfiles] = useState<ScoutProfile[]>([]); const [profile, setProfile] = useState<ScoutProfile | null>(null); const [reports, setReports] = useState<ScoutFieldReport[]>([]); const [profilePage, setProfilePage] = useState(1); const [reportPage, setReportPage] = useState(1); const [profileTotal, setProfileTotal] = useState(0); const [reportTotal, setReportTotal] = useState(0); const [profileTotalPages, setProfileTotalPages] = useState(0); const [reportTotalPages, setReportTotalPages] = useState(0); const [profileHasNext, setProfileHasNext] = useState(false); const [reportHasNext, setReportHasNext] = useState(false); const [isLoading, setIsLoading] = useState(false); const [isDetailLoading, setIsDetailLoading] = useState(false); const [activeAction, setActiveAction] = useState<Action | null>(null); const [errorMessage, setErrorMessage] = useState(''); const [actionErrorMessage, setActionErrorMessage] = useState(''); const [successMessage, setSuccessMessage] = useState(''); const actionRef = useRef<Action | null>(null); const queries = useRef({ profileStatus, reportStatus, profilePage, reportPage })
  const fail = useCallback((error: unknown, fallback: string) => { if (isApiError<AdminScoutErrorResponse>(error)) { if (error.response?.data?.code === 'INVALID_TOKEN' || error.category === 'unauthorized') clearAuth(); return getAuthErrorMessage(error, { fallbackMessage: fallback, categoryMessages: CATEGORIES }) } return fallback }, [clearAuth])
  const fetchProfiles = useCallback(async (status = queries.current.profileStatus, page = queries.current.profilePage) => { setIsLoading(true); setErrorMessage(''); try { const data = await api.getAdminScoutProfiles({ status: status || undefined, page, limit: 10 }); setProfiles(data.profiles); setProfileStatus(status); setProfilePage(data.page); setProfileTotal(data.totalCount); setProfileTotalPages(data.totalPages); setProfileHasNext(data.hasNext); queries.current = { ...queries.current, profileStatus: status, profilePage: data.page }; return true } catch (error) { setProfiles([]); setErrorMessage(fail(error, 'Scout 프로필 목록을 불러오지 못했습니다.')); logDebugError('관리자 Scout 프로필 목록 조회 실패', error); return false } finally { setIsLoading(false) } }, [fail])
  const fetchProfile = useCallback(async (userId: number) => { setIsDetailLoading(true); setErrorMessage(''); try { const data = await api.getAdminScoutProfile(userId); setProfile(data); return data } catch (error) { setProfile(null); setErrorMessage(fail(error, 'Scout 프로필 상세를 불러오지 못했습니다.')); logDebugError('관리자 Scout 프로필 상세 조회 실패', error); return null } finally { setIsDetailLoading(false) } }, [fail])
  const fetchReports = useCallback(async (status = queries.current.reportStatus, page = queries.current.reportPage) => { setIsLoading(true); setErrorMessage(''); try { const data = await api.getAdminScoutFieldReports({ status: status || undefined, page, limit: 10 }); setReports(data.reports); setReportStatus(status); setReportPage(data.page); setReportTotal(data.totalElements); setReportTotalPages(data.totalPages); setReportHasNext(data.hasNext); queries.current = { ...queries.current, reportStatus: status, reportPage: data.page }; return true } catch (error) { setReports([]); setErrorMessage(fail(error, 'Scout 현장 제보를 불러오지 못했습니다.')); logDebugError('관리자 Scout 현장 제보 조회 실패', error); return false } finally { setIsLoading(false) } }, [fail])
  const run = useCallback(async <T,>(action: Action, request: () => Promise<T>, success: string, refresh: () => Promise<unknown>) => { if (actionRef.current) return null; actionRef.current = action; setActiveAction(action); setActionErrorMessage(''); setSuccessMessage(''); try { const data = await request(); setSuccessMessage(success); await refresh(); return data } catch (error) { setActionErrorMessage(fail(error, 'Scout 작업을 처리하지 못했습니다.')); logDebugError(`관리자 Scout ${action} 실패`, error); return null } finally { actionRef.current = null; setActiveAction(null) } }, [fail])
  const reviewProfile = useCallback((userId: number, action: 'approve' | 'suspend' | 'revoke', reason: string) => run('profile', () => api.reviewAdminScoutProfile(userId, action, reason), 'Scout 프로필 상태를 변경했습니다.', async () => { await fetchProfiles(); await fetchProfile(userId) }), [fetchProfile, fetchProfiles, run])
  const grantEligibility = useCallback((userId: number, request: { eligibleFrom: string; eligibleUntil?: string; reason?: string }) => run('eligibility', () => api.grantAdminScoutEligibility(userId, request), 'Scout 활동 자격을 부여했습니다.', () => fetchProfile(userId)), [fetchProfile, run])
  const reviewEligibility = useCallback((userId: number, action: 'suspend' | 'revoke', reason: string) => run('eligibility', () => api.reviewAdminScoutEligibility(userId, action, reason), 'Scout 활동 자격 상태를 변경했습니다.', () => fetchProfile(userId)), [fetchProfile, run])
  const reviewReport = useCallback((reportId: number, decision: 'ACCEPTED' | 'REJECTED', note: string) => run('report', () => api.reviewAdminScoutFieldReport(reportId, decision, note), 'Scout 현장 제보를 심사했습니다.', () => fetchReports()), [fetchReports, run])
  useEffect(() => { void fetchProfiles('PENDING', 1); void fetchReports('SUBMITTED', 1) }, [fetchProfiles, fetchReports])
  return { profileStatus, reportStatus, profiles, profile, reports, profilePage, reportPage, profileTotal, reportTotal, profileTotalPages, reportTotalPages, profileHasNext, reportHasNext, isLoading, isDetailLoading, activeAction, errorMessage, actionErrorMessage, successMessage, fetchProfiles, fetchProfile, fetchReports, reviewProfile, grantEligibility, reviewEligibility, reviewReport }
}
