import { useCallback, useEffect, useRef, useState } from 'react'
import { useAutoDismissMessage } from './useAutoDismissMessage'
import * as api from '../api/adminVisitorVerificationApi'
import { getAuthErrorMessage } from '../api/authError'
import { isApiError } from '../api/customAxios'
import type { AdminVisitorVerificationErrorResponse, VisitorVerificationCorrection, VisitorVerificationReport, VisitorVerificationStatus } from '../types/adminVisitorVerification.types'
import { logDebugError } from '../utils/debugLogger'
import { useAuth } from './useAuth'

type Kind = 'reports' | 'corrections'
const CATEGORY_MESSAGES = { unauthorized: '로그인이 필요합니다.', forbidden: '관리자 권한이 필요합니다.', 'not-found': '제보 또는 정정 요청을 찾을 수 없습니다.', conflict: '이미 심사되었거나 현재 제보 상태와 충돌합니다.', network: '서버에 연결할 수 없습니다.', 'request-blocked': '서버 응답을 읽지 못했습니다.', timeout: '응답이 지연되고 있습니다.', server: '서버 오류가 발생했습니다.' }
function msg(error: unknown, fallback: string) { return isApiError<AdminVisitorVerificationErrorResponse>(error) ? getAuthErrorMessage(error, { fallbackMessage: fallback, categoryMessages: CATEGORY_MESSAGES }) : fallback }

export function useAdminVisitorVerifications() {
  const { clearAuth } = useAuth(); const [reportStatus, setReportStatus] = useState<VisitorVerificationStatus | ''>('SUBMITTED'); const [correctionStatus, setCorrectionStatus] = useState<VisitorVerificationStatus | ''>('SUBMITTED'); const [reports, setReports] = useState<VisitorVerificationReport[]>([]); const [corrections, setCorrections] = useState<VisitorVerificationCorrection[]>([]); const [reportPage, setReportPage] = useState(1); const [correctionPage, setCorrectionPage] = useState(1); const [reportTotal, setReportTotal] = useState(0); const [correctionTotal, setCorrectionTotal] = useState(0); const [reportTotalPages, setReportTotalPages] = useState(0); const [correctionTotalPages, setCorrectionTotalPages] = useState(0); const [reportHasNext, setReportHasNext] = useState(false); const [correctionHasNext, setCorrectionHasNext] = useState(false); const [isLoading, setIsLoading] = useState(false); const [isReviewing, setIsReviewing] = useState(false); const [errorMessage, setErrorMessage] = useState(''); const [actionErrorMessage, setActionErrorMessage] = useState('')
  useAutoDismissMessage(actionErrorMessage, setActionErrorMessage); const [successMessage, setSuccessMessage] = useState('')
  useAutoDismissMessage(successMessage, setSuccessMessage); const reviewRef = useRef(false); const queryRef = useRef({ reportStatus, correctionStatus, reportPage, correctionPage })
  const fail = useCallback((error: unknown, fallback: string) => { if (isApiError<AdminVisitorVerificationErrorResponse>(error) && (error.response?.data?.code === 'INVALID_TOKEN' || error.category === 'unauthorized')) clearAuth(); return msg(error, fallback) }, [clearAuth])
  const fetchItems = useCallback(async (kind: Kind, status?: VisitorVerificationStatus | '', page?: number) => { setIsLoading(true); setErrorMessage(''); const nextStatus = status ?? (kind === 'reports' ? queryRef.current.reportStatus : queryRef.current.correctionStatus); const nextPage = page ?? (kind === 'reports' ? queryRef.current.reportPage : queryRef.current.correctionPage); try { if (kind === 'reports') { const data = await api.getAdminVisitorVerificationReports({ status: nextStatus || undefined, page: nextPage, limit: 10 }); setReports(data.reports); setReportStatus(nextStatus); setReportPage(data.page); setReportTotal(data.totalElements); setReportTotalPages(data.totalPages); setReportHasNext(data.hasNext); queryRef.current = { ...queryRef.current, reportStatus: nextStatus, reportPage: data.page } } else { const data = await api.getAdminVisitorVerificationCorrections({ status: nextStatus || undefined, page: nextPage, limit: 10 }); setCorrections(data.corrections); setCorrectionStatus(nextStatus); setCorrectionPage(data.page); setCorrectionTotal(data.totalElements); setCorrectionTotalPages(data.totalPages); setCorrectionHasNext(data.hasNext); queryRef.current = { ...queryRef.current, correctionStatus: nextStatus, correctionPage: data.page } } return true } catch (error) { if (kind === 'reports') setReports([]); else setCorrections([]); setErrorMessage(fail(error, '방문자 검증 심사 목록을 불러오지 못했습니다.')); logDebugError(`관리자 방문자 검증 ${kind} 조회 실패`, error); return false } finally { setIsLoading(false) } }, [fail])
  const review = useCallback(async (kind: Kind, id: number, decision: 'ACCEPTED' | 'REJECTED', note: string) => { if (reviewRef.current) return null; reviewRef.current = true; setIsReviewing(true); setActionErrorMessage(''); setSuccessMessage(''); try { const data = kind === 'reports' ? await api.reviewAdminVisitorVerificationReport(id, decision, note) : await api.reviewAdminVisitorVerificationCorrection(id, decision, note); setSuccessMessage(decision === 'ACCEPTED' ? '심사 요청을 승인했습니다.' : '심사 요청을 반려했습니다.'); await fetchItems(kind); return data } catch (error) { setActionErrorMessage(fail(error, '방문자 검증 심사를 처리하지 못했습니다.')); logDebugError(`관리자 방문자 검증 ${kind} 심사 실패`, error); return null } finally { reviewRef.current = false; setIsReviewing(false) } }, [fail, fetchItems])
  useEffect(() => { void fetchItems('reports', 'SUBMITTED', 1); void fetchItems('corrections', 'SUBMITTED', 1) }, [fetchItems])
  return { reportStatus, correctionStatus, reports, corrections, reportPage, correctionPage, reportTotal, correctionTotal, reportTotalPages, correctionTotalPages, reportHasNext, correctionHasNext, isLoading, isReviewing, errorMessage, actionErrorMessage, successMessage, fetchItems, review }
}
