import { useCallback,useEffect,useRef,useState } from 'react'
import { useAutoDismissMessage } from './useAutoDismissMessage'
import * as api from '../api/adminS3OrphanApi'; import { getAuthErrorMessage } from '../api/authError'; import { isApiError } from '../api/customAxios'; import type { AdminS3OrphanErrorResponse,S3OrphanDeleteResult,S3OrphanDryRun,S3OrphanReport,S3OrphanReportStatus } from '../types/adminS3Orphan.types'; import { logDebugError } from '../utils/debugLogger'; import { useAuth } from './useAuth'
const C={unauthorized:'로그인이 필요합니다.',forbidden:'관리자 권한이 필요합니다.','not-found':'완료된 S3 리포트를 찾을 수 없습니다.',conflict:'현재 리포트 상태에서는 처리할 수 없습니다.',network:'서버에 연결할 수 없습니다.','request-blocked':'서버 응답을 읽지 못했습니다.',timeout:'응답이 지연되고 있습니다.',server:'S3 또는 서버 오류가 발생했습니다.'}
export function useAdminS3Orphans(){
 const{clearAuth}=useAuth(); const[dryRun,setDryRun]=useState<S3OrphanDryRun|null>(null); const[status,setStatus]=useState<S3OrphanReportStatus|null>(null); const[report,setReport]=useState<S3OrphanReport|null>(null); const[result,setResult]=useState<S3OrphanDeleteResult|null>(null); const[isLoading,setIsLoading]=useState(false); const[activeAction,setActiveAction]=useState<'refresh'|'delete'|null>(null); const[errorMessage,setErrorMessage]=useState(''); const[successMessage,setSuccessMessage]=useState('')
  useAutoDismissMessage(successMessage, setSuccessMessage); const action=useRef(false)
 const msg=useCallback((e:unknown,f:string)=>{if(!isApiError<AdminS3OrphanErrorResponse>(e))return f;if(e.response?.data?.code==='INVALID_TOKEN'||e.category==='unauthorized')clearAuth();return getAuthErrorMessage(e,{fallbackMessage:f,categoryMessages:C})},[clearAuth])
 const fetchDryRun=useCallback(async(prefix='map/',limit=1000)=>{setIsLoading(true);setErrorMessage('');try{setDryRun(await api.getAdminS3OrphanDryRun(prefix,limit));return true}catch(e){setErrorMessage(msg(e,'S3 dry-run 리포트를 불러오지 못했습니다.'));logDebugError('S3 dry-run 조회 실패',e);return false}finally{setIsLoading(false)}},[msg])
 const fetchReport=useCallback(async(reportId?:string,page=1)=>{setIsLoading(true);setErrorMessage('');try{const data=await api.getAdminS3OrphanReport(reportId,page,5);setReport(data);setStatus(data);return true}catch(e){setReport(null);setErrorMessage(msg(e,'S3 고아 객체 리포트를 불러오지 못했습니다.'));logDebugError('S3 리포트 조회 실패',e);return false}finally{setIsLoading(false)}},[msg])
 const fetchStatus=useCallback(async(reportId?:string)=>{try{const data=await api.getAdminS3OrphanReportStatus(reportId);setStatus(data);if(data.status==='COMPLETED')await fetchReport(data.reportId,1);return data}catch(e){setErrorMessage(msg(e,'S3 리포트 상태를 불러오지 못했습니다.'));return null}},[fetchReport,msg])
 const refresh=useCallback(async()=>{if(action.current)return null;action.current=true;setActiveAction('refresh');setErrorMessage('');setSuccessMessage('');setResult(null);try{const data=await api.refreshAdminS3OrphanReport();setStatus(data);setReport(null);setSuccessMessage(data.status==='RUNNING'?'리포트 생성을 시작했습니다.':'리포트를 갱신했습니다.');return data}catch(e){setErrorMessage(msg(e,'S3 리포트 생성을 시작하지 못했습니다.'));return null}finally{action.current=false;setActiveAction(null)}},[msg])
 const remove=useCallback(async(keys:string[])=>{if(!report||action.current)return null;action.current=true;setActiveAction('delete');setErrorMessage('');setSuccessMessage('');try{const data=await api.deleteAdminS3Orphans(report.reportId,keys);setResult(data);setSuccessMessage(`${data.deletedKeyCount}개 객체를 삭제했고 ${data.failedKeyCount}개가 실패했습니다.`);await fetchReport(report.reportId,report.page);return data}catch(e){setErrorMessage(msg(e,'S3 고아 객체를 삭제하지 못했습니다.'));logDebugError('S3 고아 객체 삭제 실패',e);return null}finally{action.current=false;setActiveAction(null)}},[fetchReport,msg,report])
 useEffect(()=>{void fetchDryRun();void fetchStatus()},[fetchDryRun,fetchStatus]); useEffect(()=>{if(status?.status!=='RUNNING')return;const id=window.setTimeout(()=>void fetchStatus(status.reportId),3000);return()=>window.clearTimeout(id)},[fetchStatus,status])
 return{dryRun,status,report,result,isLoading,activeAction,errorMessage,successMessage,fetchDryRun,fetchReport,fetchStatus,refresh,remove}
}
