import { useCallback, useEffect, useRef, useState } from 'react'
import * as api from '../api/adminMerchantPlaceClaimApi'
import { getAuthErrorMessage } from '../api/authError'
import { isApiError } from '../api/customAxios'
import type { AdminMerchantPlaceClaimAttachment, AdminMerchantPlaceClaimErrorResponse, MerchantPlaceClaim, MerchantPlaceClaimListItem, MerchantPlaceClaimStatus } from '../types/adminMerchantPlaceClaim.types'
import { logDebugError } from '../utils/debugLogger'
import { useAuth } from './useAuth'
const CATEGORIES = { unauthorized: '로그인이 필요합니다.', forbidden: '관리자 권한이 필요합니다.', 'not-found': 'Claim 요청을 찾을 수 없습니다.', conflict: '다른 관리자가 먼저 처리했습니다. 최신 상세를 다시 확인해주세요.', network: '서버에 연결할 수 없습니다.', 'request-blocked': '서버 응답을 읽지 못했습니다.', timeout: '응답이 지연되고 있습니다.', server: '서버 오류가 발생했습니다.' }
export function useAdminMerchantPlaceClaims() {
  const { clearAuth } = useAuth(); const [status,setStatus] = useState<MerchantPlaceClaimStatus | ''>('PENDING'); const [claims,setClaims] = useState<MerchantPlaceClaimListItem[]>([]); const [detail,setDetail] = useState<MerchantPlaceClaim | null>(null); const [attachments,setAttachments] = useState<AdminMerchantPlaceClaimAttachment[]>([]); const [page,setPage] = useState(1); const [total,setTotal] = useState(0); const [totalPages,setTotalPages] = useState(0); const [hasNext,setHasNext] = useState(false); const [isLoading,setIsLoading] = useState(false); const [isDetailLoading,setIsDetailLoading] = useState(false); const [isAttachmentLoading,setIsAttachmentLoading] = useState(false); const [hasLoadedAttachments,setHasLoadedAttachments] = useState(false); const [downloadingAttachmentId,setDownloadingAttachmentId] = useState<number | null>(null); const [isReviewing,setIsReviewing] = useState(false); const [errorMessage,setErrorMessage] = useState(''); const [attachmentErrorMessage,setAttachmentErrorMessage] = useState(''); const [actionErrorMessage,setActionErrorMessage] = useState(''); const [successMessage,setSuccessMessage] = useState(''); const reviewRef = useRef(false); const detailRequestRef = useRef(0); const attachmentRequestRef = useRef(0); const queryRef = useRef({ status, page })
  const msg = useCallback((error: unknown, fallback: string) => { if (!isApiError<AdminMerchantPlaceClaimErrorResponse>(error)) return fallback; if (error.response?.data?.code === 'INVALID_TOKEN' || error.category === 'unauthorized') clearAuth(); return getAuthErrorMessage(error, { fallbackMessage: fallback, categoryMessages: CATEGORIES }) }, [clearAuth])
  const fetchClaims = useCallback(async (nextStatus: MerchantPlaceClaimStatus | '' = queryRef.current.status, nextPage = queryRef.current.page) => { setIsLoading(true); setErrorMessage(''); try { const data = await api.getAdminMerchantPlaceClaims({ status: nextStatus || undefined, page: nextPage, limit: 20 }); setClaims(data.claims); setStatus(nextStatus); setPage(data.page); setTotal(data.totalElements); setTotalPages(data.totalPages); setHasNext(data.hasNext); queryRef.current = { status: nextStatus, page: data.page }; return true } catch (error) { setClaims([]); setErrorMessage(msg(error,'Claim 요청 목록을 불러오지 못했습니다.')); logDebugError('관리자 Merchant 장소 Claim 목록 조회 실패',error); return false } finally { setIsLoading(false) } }, [msg])
  const fetchAttachments = useCallback(async (claimId: number) => { const requestId = attachmentRequestRef.current + 1; attachmentRequestRef.current = requestId; setIsAttachmentLoading(true); setHasLoadedAttachments(false); setAttachmentErrorMessage(''); setAttachments([]); try { const data = await api.getAdminMerchantPlaceClaimAttachments(claimId); if (requestId !== attachmentRequestRef.current) return false; setAttachments(data); setHasLoadedAttachments(true); return true } catch (error) { if (requestId !== attachmentRequestRef.current) return false; setAttachmentErrorMessage(msg(error,'Claim 증빙 파일 목록을 불러오지 못했습니다.')); logDebugError('관리자 Merchant 장소 Claim 증빙 파일 목록 조회 실패',error); return false } finally { if (requestId === attachmentRequestRef.current) setIsAttachmentLoading(false) } }, [msg])
  const fetchDetail = useCallback(async (claimId: number) => { const requestId = detailRequestRef.current + 1; detailRequestRef.current = requestId; setIsDetailLoading(true); setErrorMessage(''); setDetail(null); void fetchAttachments(claimId); try { const data = await api.getAdminMerchantPlaceClaim(claimId); if (requestId !== detailRequestRef.current) return null; setDetail(data); return data } catch (error) { if (requestId !== detailRequestRef.current) return null; attachmentRequestRef.current += 1; setDetail(null); setAttachments([]); setHasLoadedAttachments(false); setIsAttachmentLoading(false); setErrorMessage(msg(error,'Claim 요청 상세를 불러오지 못했습니다.')); logDebugError('관리자 Merchant 장소 Claim 상세 조회 실패',error); return null } finally { if (requestId === detailRequestRef.current) setIsDetailLoading(false) } }, [fetchAttachments,msg])
  const downloadAttachment = useCallback(async (claimId: number, attachment: AdminMerchantPlaceClaimAttachment) => { if (downloadingAttachmentId !== null) return false; setDownloadingAttachmentId(attachment.id); setActionErrorMessage(''); try { const file = await api.downloadAdminMerchantPlaceClaimAttachment(claimId, attachment.id); const href = URL.createObjectURL(file); const link = document.createElement('a'); link.href = href; const extension = { 'application/pdf': 'pdf', 'image/jpeg': 'jpg', 'image/png': 'png', 'image/webp': 'webp' }[attachment.contentType.split(';', 1)[0].toLowerCase()] ?? 'bin'; link.download = `claim-${claimId}-${attachment.documentType.toLowerCase()}-${attachment.id}.${extension}`; document.body.appendChild(link); link.click(); link.remove(); URL.revokeObjectURL(href); return true } catch (error) { setActionErrorMessage(msg(error,'Claim 증빙 파일을 다운로드하지 못했습니다.')); logDebugError('관리자 Merchant 장소 Claim 증빙 파일 다운로드 실패',error); return false } finally { setDownloadingAttachmentId(null) } }, [downloadingAttachmentId,msg])
  const review = useCallback(async (approved: boolean, reason: string) => { if (!detail || reviewRef.current) return null; reviewRef.current = true; setIsReviewing(true); setActionErrorMessage(''); setSuccessMessage(''); try { const data = await api.reviewAdminMerchantPlaceClaim(detail.id,approved,reason,detail.version); setDetail(data); setSuccessMessage(approved ? 'Claim 요청을 승인했습니다.' : 'Claim 요청을 거절했습니다.'); await fetchClaims(); return data } catch (error) { setActionErrorMessage(msg(error,'Claim 심사를 처리하지 못했습니다.')); logDebugError('관리자 Merchant 장소 Claim 심사 실패',error); if (isApiError(error) && error.category === 'conflict') await fetchDetail(detail.id); return null } finally { reviewRef.current = false; setIsReviewing(false) } }, [detail,fetchClaims,fetchDetail,msg])
  useEffect(() => { void fetchClaims('PENDING',1) }, [fetchClaims])
  return { status,claims,detail,attachments,page,total,totalPages,hasNext,isLoading,isDetailLoading,isAttachmentLoading,hasLoadedAttachments,downloadingAttachmentId,isReviewing,errorMessage,attachmentErrorMessage,actionErrorMessage,successMessage,fetchClaims,fetchDetail,fetchAttachments,downloadAttachment,review }
}
