import { useState, type FormEvent } from 'react'
import { useNavigate } from 'react-router-dom'
import { AdminNotificationButton } from '../../components/adminNotification/AdminNotificationButton'
import { ADMIN_MAIN_SCROLL_AREA_ID } from '../../constants/layout'
import { useAdminUserRoles } from '../../hooks/useAdminUserRoles'
import { useAuth } from '../../hooks/useAuth'
import type { AdminRole } from '../../types/adminUserRole.types'
import * as Shell from '../place/PlaceManagePage.styles'
import * as Shared from '../placeMerge/PlaceMergePage.styles'
import * as S from '../placeVerification/PlaceVerificationPage.styles'

const ROLES: Record<AdminRole, string> = { SUPER_ADMIN: '최고 관리자', CONTENT_MODERATOR: '콘텐츠 운영자', MERCHANT_OPERATOR: 'Merchant 운영자', SUPPORT_OPERATOR: '사용자 지원 운영자', ANALYST: '분석 담당자' }
const PERMISSIONS: Record<string, string> = { ADMIN_ROLE_MANAGE: '관리자 역할 관리', USER_READ: '사용자 조회', USER_SANCTION: '사용자 제재', PLACE_READ: '장소 조회', PLACE_MODERATE: '장소 운영', MERCHANT_REVIEW: 'Merchant 심사', REPORT_REVIEW: '신고 심사', SCOUT_REVIEW: 'Scout 심사', DASHBOARD_READ: '대시보드 조회', AUDIT_READ: '감사 로그 조회', OUTBOX_RECOVERY: 'Outbox 복구' }
type Dialog = { action: 'assign' | 'revoke'; role: AdminRole } | null
function date(value?: string | null) { if (!value) return '해당 없음'; const d = new Date(value); return Number.isNaN(d.getTime()) ? value : new Intl.DateTimeFormat('ko-KR', { dateStyle: 'medium', timeStyle: 'short' }).format(d) }

function UserRolePage() {
  const navigate = useNavigate(); const { logout, user } = useAuth(); const hook = useAdminUserRoles()
  const [userIdInput, setUserIdInput] = useState(''); const [dialog, setDialog] = useState<Dialog>(null); const [reason, setReason] = useState(''); const [formError, setFormError] = useState('')
  const adminIdentifier = user?.username || (typeof user?.id === 'number' ? `ID ${user.id}` : '관리자 계정')
  const activeRoles = new Set(hook.assignments.filter((item) => item.status === 'ACTIVE').map((item) => item.role))
  const search = (event: FormEvent) => { event.preventDefault(); const id = Number(userIdInput); if (!Number.isSafeInteger(id) || id <= 0) { setFormError('관리자 사용자 ID를 양의 정수로 입력해주세요.'); return } setFormError(''); void hook.fetchRoles(id) }
  const open = (action: 'assign' | 'revoke', role: AdminRole) => { setReason(''); setFormError(''); setDialog({ action, role }) }
  const submit = async () => { if (!dialog || hook.isMutating) return; if (!reason.trim()) { setFormError('권한 변경 사유를 입력해주세요.'); return } if (await hook.mutate(dialog.role, dialog.action, reason.trim())) setDialog(null) }

  return <Shell.AppShell>
    <Shell.SideNav aria-label="관리자 메뉴"><Shell.SideHeader><Shell.BrandLockup><Shell.BrandLogo src="/pingdom-logo.png" alt="PingDom" /></Shell.BrandLockup></Shell.SideHeader><Shell.SideMenu><Shell.MenuButton type="button" $active onClick={() => navigate('/dashboard')}><Shell.MaterialIcon aria-hidden="true">dashboard</Shell.MaterialIcon><span>대시보드</span></Shell.MenuButton><Shell.MenuButton type="button" onClick={() => navigate('/places')}><Shell.MaterialIcon aria-hidden="true">location_on</Shell.MaterialIcon><span>장소 관리</span></Shell.MenuButton><Shell.MenuButton type="button" onClick={() => navigate('/main')}><Shell.MaterialIcon aria-hidden="true">description</Shell.MaterialIcon><span>게시글 관리</span></Shell.MenuButton><Shell.MenuButton type="button" onClick={() => navigate('/bans')}><Shell.MaterialIcon aria-hidden="true">block</Shell.MaterialIcon><span>사용자 밴</span></Shell.MenuButton></Shell.SideMenu><Shell.SideFooter><Shell.AdminProfile><Shell.AdminProfileIcon><Shell.MaterialIcon aria-hidden="true">admin_panel_settings</Shell.MaterialIcon></Shell.AdminProfileIcon><Shell.AdminProfileText><strong>{adminIdentifier}</strong><span>관리자</span></Shell.AdminProfileText></Shell.AdminProfile><Shell.LogoutButton type="button" onClick={() => { void logout(); navigate('/login', { replace: true }) }}><Shell.MaterialIcon aria-hidden="true">logout</Shell.MaterialIcon><span>로그아웃</span></Shell.LogoutButton></Shell.SideFooter></Shell.SideNav>
    <Shell.MainArea id={ADMIN_MAIN_SCROLL_AREA_ID}><Shell.TopBar><Shell.TopTitleGroup><Shell.TopTitle>관리자 역할 관리</Shell.TopTitle></Shell.TopTitleGroup><Shell.TopActions><AdminNotificationButton /></Shell.TopActions></Shell.TopBar><Shared.Content><Shared.PageStack>
      <Shared.PageHeader><div><Shared.Eyebrow>사용자 관리 &gt; 관리자 역할</Shared.Eyebrow><Shared.PageTitle>관리자 역할 및 권한 이력</Shared.PageTitle><Shared.PageDescription>관리자 사용자 ID를 조회하고 활성 역할과 변경 이력을 확인한 뒤 권한을 부여하거나 회수합니다.</Shared.PageDescription></div><Shared.HeaderActions><Shared.HeaderButton type="button" onClick={() => navigate('/bans')}>사용자 밴 관리</Shared.HeaderButton></Shared.HeaderActions></Shared.PageHeader>
      <S.SearchBar as="form" onSubmit={search}><S.Field>관리자 사용자 ID<S.Input value={userIdInput} inputMode="numeric" placeholder="예: 42" onChange={(event) => { setUserIdInput(event.target.value); setFormError('') }} /></S.Field><Shared.PrimaryButton type="submit" disabled={hook.isLoading}>{hook.isLoading ? '조회 중' : '역할 조회'}</Shared.PrimaryButton></S.SearchBar>
      {formError ? <Shared.Notice $variant="error">{formError}</Shared.Notice> : null}{hook.errorMessage ? <Shared.Notice $variant="error">{hook.errorMessage}</Shared.Notice> : null}{hook.actionErrorMessage ? <Shared.Notice $variant="error">{hook.actionErrorMessage}</Shared.Notice> : null}{hook.successMessage ? <Shared.Notice $variant="success">{hook.successMessage}</Shared.Notice> : null}
      {hook.targetUserId && user?.id === hook.targetUserId ? <Shared.DetailNotice><Shell.MaterialIcon aria-hidden="true">warning</Shell.MaterialIcon><div><strong>현재 로그인한 계정입니다.</strong>자기 역할을 회수하면 관리 기능에 다시 접근하지 못할 수 있습니다.</div></Shared.DetailNotice> : null}
      <Shared.Panel><Shared.PanelHeader><div><Shared.PanelTitle>역할 부여 상태</Shared.PanelTitle><Shared.PanelDescription>{hook.targetUserId ? `관리자 #${hook.targetUserId}의 역할을 관리합니다.` : '먼저 관리자 사용자 ID를 조회해주세요.'}</Shared.PanelDescription></div><Shared.PanelCount>{activeRoles.size}개 활성</Shared.PanelCount></Shared.PanelHeader><Shared.CompareBody>{!hook.targetUserId ? <Shared.EmptyState><strong>관리자 사용자를 조회해주세요.</strong></Shared.EmptyState> : <S.CardList>{(Object.entries(ROLES) as [AdminRole,string][]).map(([role,label]) => { const active = activeRoles.has(role); return <S.RecordCard key={role}><S.RecordHeader><div><S.RecordTitle>{label}</S.RecordTitle><S.RecordMeta>{role}</S.RecordMeta></div><S.StatusBadge $tone={active ? 'success' : undefined}>{active ? '활성' : '미부여'}</S.StatusBadge></S.RecordHeader><S.InlineActions>{active ? <Shared.SecondaryButton type="button" disabled={hook.isMutating} onClick={() => open('revoke', role)}>역할 회수</Shared.SecondaryButton> : <Shared.PrimaryButton type="button" disabled={hook.isMutating} onClick={() => open('assign', role)}>역할 부여</Shared.PrimaryButton>}</S.InlineActions></S.RecordCard> })}</S.CardList>}</Shared.CompareBody></Shared.Panel>
      <Shared.Panel><Shared.PanelHeader><div><Shared.PanelTitle>역할 변경 이력</Shared.PanelTitle><Shared.PanelDescription>최근 할당 순서로 부여자와 권한 범위를 표시합니다.</Shared.PanelDescription></div><Shared.PanelCount>{hook.assignments.length}건</Shared.PanelCount></Shared.PanelHeader><Shared.CompareBody>{hook.targetUserId && hook.assignments.length === 0 ? <Shared.EmptyState><strong>역할 변경 이력이 없습니다.</strong></Shared.EmptyState> : <S.CardList>{hook.assignments.map((item) => <S.RecordCard key={item.id}><S.RecordHeader><div><S.RecordTitle>{ROLES[item.role]}</S.RecordTitle><S.RecordMeta>이력 #{item.id} · 처리 관리자 #{item.assignedByUserId}</S.RecordMeta></div><S.StatusBadge $tone={item.status === 'ACTIVE' ? 'success' : 'danger'}>{item.status === 'ACTIVE' ? '활성' : '회수'}</S.StatusBadge></S.RecordHeader><S.DetailGrid><S.DetailItem><dt>부여 시각</dt><dd>{date(item.assignedAt)}</dd></S.DetailItem><S.DetailItem><dt>회수 시각</dt><dd>{date(item.revokedAt)}</dd></S.DetailItem></S.DetailGrid><S.RecordDescription>{item.permissions.map((permission) => PERMISSIONS[permission] || permission).join(' · ') || '전체 관리자 권한'}</S.RecordDescription></S.RecordCard>)}</S.CardList>}</Shared.CompareBody></Shared.Panel>
    </Shared.PageStack></Shared.Content></Shell.MainArea>
    {dialog ? <Shared.ModalOverlay role="presentation" onMouseDown={() => !hook.isMutating && setDialog(null)}><Shared.Modal role="dialog" aria-modal="true" aria-labelledby="role-dialog-title" onMouseDown={(event) => event.stopPropagation()}><Shared.ModalHeader><Shared.ModalTitle id="role-dialog-title">관리자 역할 {dialog.action === 'assign' ? '부여' : '회수'}</Shared.ModalTitle><Shared.ModalCloseButton type="button" aria-label="닫기" disabled={hook.isMutating} onClick={() => setDialog(null)}><Shell.MaterialIcon aria-hidden="true">close</Shell.MaterialIcon></Shared.ModalCloseButton></Shared.ModalHeader><Shared.ModalBody><Shared.ModalWarning>관리자 #{hook.targetUserId}의 {ROLES[dialog.role]} 역할을 {dialog.action === 'assign' ? '부여' : '회수'}합니다. 권한 범위가 즉시 변경될 수 있습니다.</Shared.ModalWarning><S.Section><S.Field>변경 사유 *<S.TextArea value={reason} maxLength={500} onChange={(event) => { setReason(event.target.value); setFormError('') }} /><small>{reason.length}/500</small></S.Field></S.Section>{formError || hook.actionErrorMessage ? <Shared.Notice $variant="error">{formError || hook.actionErrorMessage}</Shared.Notice> : null}</Shared.ModalBody><Shared.ModalFooter><Shared.SecondaryButton type="button" disabled={hook.isMutating} onClick={() => setDialog(null)}>취소</Shared.SecondaryButton><Shared.PrimaryButton type="button" disabled={hook.isMutating} onClick={() => void submit()}>{hook.isMutating ? '처리 중' : '변경 확정'}</Shared.PrimaryButton></Shared.ModalFooter></Shared.Modal></Shared.ModalOverlay> : null}
  </Shell.AppShell>
}

export default UserRolePage
